pipeline {
    agent any
	
    environment {
        NODE_LIST = ''
    }

    parameters {
        booleanParam(name: 'RUN_STEP_1', defaultValue: false, description: 'Run Step 1')
        booleanParam(name: 'RUN_STEP_2', defaultValue: false, description: 'Run Step 2')
        booleanParam(name: 'RUN_STEP_3', defaultValue: false, description: 'Run Step 3')
    }

    stages {
	stage('Generate Node List') {
            steps {
                script {
                    def nodeList = []
                    Jenkins.instance.nodes.each { node ->
                        if (node.getAssignedLabels().contains('node')) {
                            nodeList.add(node.getNodeName())
                        }
                    }
                    env.NODE_LIST = nodeList.join(',')
                }
            }
        }
        stage('Stop Service on All Nodes') {
            when {
                expression { return env.NODE_LIST != '' }
            }
            matrix {
                axes {
                    axis {
                        name 'NODE'
                        values "${env.NODE_LIST}".split(',')
                    }
                }
                stages {
                    stage('Stop Service') {
                        agent { label NODE }
                        steps {
                            echo "Stopping service on ${NODE}"
                            sh 'sudo systemctl stop your-service'
                        }
                    }
                }
            }
        }
        stage('Step 1') {
            when {
                expression { return params.RUN_STEP_1 }
            }
            steps {
                echo 'Running Step 1'
                // Ваши команды для Step 1
            }
        }
        stage('Step 2') {
            when {
                expression { return params.RUN_STEP_2 }
            }
            steps {
                echo 'Running Step 2'
                // Ваши команды для Step 2
            }
        }
        stage('Step 3') {
            when {
                expression { return params.RUN_STEP_3 }
            }
            steps {
                echo 'Running Step 3'
                // Ваши команды для Step 3
            }
        }
    }
}